### ISSUE TITLE
voodoojs.com not working

### ISSUE THREAD

**Issue by AkshayMathur92** [brentongunning/voodoo.js#95]
http://www.voodoojs.com/ 
return ERR_NAME_NOT_RESOLVED.

**Comment by brentgunningsc** [comment]
I lost the domain last year :( Was switching jobs and moving cities, and just dropped the ball on the renewal. Sorry all. When I noticed, I reached out to the owner Ivan (https://who.is/whois/voodoojs.com)  to make him an offer, but he is intent on not giving it up, and also not using it.

My plan is to get a new domain up for a v2 release. No definitely timeline, maybe early next year.

**Comment by brentongunning** [comment]
I lost the domain :( Was switching jobs and moving cities, and just dropped the ball on the renewal. Sorry all. When I noticed, I reached out to the owner Ivan (https://who.is/whois/voodoojs.com) to make him an offer, but he is intent on not giving it up, and also apparently not using it.

My plan is to get a new domain up for a v2 release. No definitely timeline, maybe early next year.

**Comment by snovak** [comment]
I was wondering if you got into some terrible car crash or something.  Glad to see you're still alive there @brentongunning  !  Hahah.  Bummer on the domain issue.  I'd love to see this project continue.  Cheers man.

**Comment by LeonFedotov** [comment]
Yeah man, happy to see that this project is alive, you should setup gh-pages branch and have it hosted on voodoo.github.io



—
Leon

**Comment by brentgunningsc** [comment]
@snovak Haha, thanks man. The project had to take a back seat to everything else for a while, but there's still a ton I want to do! Promise I'll carve out more time in 2016.

@LeonFedotov That's a great suggestion! Let me try that.

**Comment by brentgunningsc** [comment]
@snovak Haha, thanks man. The project had to take a back seat to everything else for a while, but there's still a ton I want to do! Promise I'll carve out more time in 2016.

@LeonFedotov That's a great suggestion! Let me try that.

**Comment by brentongunning** [comment]
@snovak Haha, thanks man. The project had to take a back seat to everything else for a while, but there's still a ton I want to do! Promise I'll carve out more time in 2016.

@LeonFedotov That's a great suggestion! Let me try that.

**Comment by LeonFedotov** [comment]
Amazing!
